name: build-push-docker-image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    
    strategy:
      fail-fast: false
      matrix:
        php_tag: [ "3.22", "3.21", "3.20", "3.19"]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      
      - name: Define image names
        id: names
        run: |
          echo "ghcr=ghcr.io/bilyboy785/alpine-base" >> $GITHUB_OUTPUT
          echo "dh=docker.io/martinbouillaud/alpine-base" >> $GITHUB_OUTPUT

      - name: Docker metadata (only <version> tags)
        id: meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: |
            ${{ steps.names.outputs.ghcr }}
            ${{ steps.names.outputs.dh }}
          tags: |
            type=raw,value=${{ matrix.php_tag }}
          annotations: |
            org.opencontainers.image.title=alpine-base
            org.opencontainers.image.description=Base Alpine image for multi purposes
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ matrix.php_tag }}
            org.opencontainers.image.licenses=Apache-2.0

      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_TAG=${{ matrix.php_tag }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max